#!/usr/bin/env bash
# Task 1

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee -a /var/www/html/index.html
sudo systemctl restart nginx
