#!/usr/bin/env bash
# Task 1

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "
<html>
<head>
    <meta charset="utf-8">
    <title>Hello, Nginx!</title>
</head>
<body>
    <h1>Holberton School</h1>
    <p>We have just configured our Nginx web server on Ubuntu Server!</p>
</body>
</html>" | sudo tee -a /var/www/html/index.html
