#!/usr/bin/env bash
# Task 3

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee -a /var/www/html/index.html

srvr="^server {$"
add="server {\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"

sudo sed -i 's,'"$srvr"','"$add"',' "$file"
sudo service nginx restart
