#!/usr/bin/env bash
# Task 3

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "
<html>
<head>
    <meta charset='utf-8'>
    <title>Hello, Nginx!</title>
</head>
<body>
    <h1>Holberton School</h1>
    <p>We have just configured our Nginx web server on Ubuntu Server!</p>
</body>
</html>" | sudo tee -a /var/www/html/index.html

sudo mkdir /var/www/error
sudo touch /var/www/error/custom_404.html
sudo echo "Ceci n'est pas une page" | sudo tee -a /var/www/error/custom_404.html

srvr="^server {$"
add="server {\n\trewrite ^/redirectme https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\
\n\terror_page 404 /custom_404.html;\
\n\tlocation = /custom_404.html {\
\n\t\troot /var/www/error;\
\n\t\tinternal;\
\n\t}"
file="/etc/nginx/sites-available/default"

sudo sed -i 's,'"$srvr"','"$add"',' "$file"

sudo service nginx reload
