#!/usr/bin/env bash
# Task 1
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo "listen www
    bind :80
    server 1613-web-01 34.73.244.83:80 check
    server 1613-web-02 35.175.186.218:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
