#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
c=1
while ((c<=100))
do
	if ! ((c%15)) ; then
		echo "FizzBuzz"
	elif ! ((c%3)) ; then
		echo "Fizz"
	elif ! ((c%5)) ; then
		echo "Buzz"
	else
		echo $c
	fi
	((c++))
done
