#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
c=1
while ((c<=20))
do
	printf "%d\n" $c
	case $c in

	"4")
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((c++))
done
#	if [[ $c -eq 4 ]]
#	then
#	elif [[ $c -eq 9 ]]
#	then
#	elif [[ $c -eq 17 ]]
#	then
#	fi
#	((c++))
