#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
hours=0
minutes=1
while ((hours<=12))
do
	printf "Hour: %d\n" $hours
	((hours++))
	while ((minutes<=59))
	do
		printf "%d\n" $minutes
		((minutes++))
	done
	minutes=1
done
