#!/usr/bin/env bash
# configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i '/localhost/s/127.0.0.1/127.0.0.2/g' ~/hosts.new
#sed -i '/facebook/s/.*\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*/8.8.8.8\tfacebook/g' ~/hosts.new
sed -i  '/facebook/d' ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
